# Generated by Django 4.1.4 on 2022-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feature_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='surname',
            field=models.CharField(default='Nkasi', max_length=50),
        ),
    ]
